/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetocontador;

import javax.swing.DefaultListModel;

/**
 *
 * @author mateus
 */
public class TelaContador extends javax.swing.JFrame {

    /**
     * Creates new form TelaContador
     */
    public TelaContador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sld1 = new javax.swing.JSlider();
        sld2 = new javax.swing.JSlider();
        sld3 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnContar = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCont = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sld1.setMaximum(5);
        sld1.setValue(0);
        sld1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sld1StateChanged(evt);
            }
        });
        getContentPane().add(sld1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 30, -1, -1));

        sld2.setMaximum(20);
        sld2.setMinimum(6);
        sld2.setValue(6);
        sld2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sld2StateChanged(evt);
            }
        });
        getContentPane().add(sld2, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 102, -1, -1));

        sld3.setMaximum(5);
        sld3.setMinimum(1);
        sld3.setValue(1);
        sld3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sld3StateChanged(evt);
            }
        });
        getContentPane().add(sld3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        jLabel1.setText("Início");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 56, -1, -1));

        jLabel2.setText("Fim");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 138, -1, -1));

        jLabel3.setText("Passo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 216, -1, -1));

        btnContar.setText("Contar");
        btnContar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarActionPerformed(evt);
            }
        });
        getContentPane().add(btnContar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 99, 40));
        getContentPane().add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 55, 19));
        getContentPane().add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 85, 28));
        getContentPane().add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 76, 22));

        jScrollPane1.setViewportView(lstCont);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 130, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sld1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sld1StateChanged
        int inicio = sld1.getValue();
        lbl1.setText(Integer.toString(inicio));
    }//GEN-LAST:event_sld1StateChanged

    private void sld2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sld2StateChanged
        int fim = sld2.getValue();
        lbl2.setText(Integer.toString(fim));
    }//GEN-LAST:event_sld2StateChanged

    private void sld3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sld3StateChanged
        int passo = sld3.getValue();
        lbl3.setText(Integer.toString(passo));
    }//GEN-LAST:event_sld3StateChanged

    private void btnContarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarActionPerformed
        int inicio = sld1.getValue();
        int fim = sld2.getValue();
        int passo = sld3.getValue();
        
        DefaultListModel lista = new DefaultListModel();
        
        for(int i=inicio;i<=fim;i+=passo){
            lista.addElement(i);
        }
        lstCont.setModel(lista);
    }//GEN-LAST:event_btnContarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaContador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaContador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaContador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaContador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaContador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JList lstCont;
    private javax.swing.JSlider sld1;
    private javax.swing.JSlider sld2;
    private javax.swing.JSlider sld3;
    // End of variables declaration//GEN-END:variables
}
