/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author mateus
 */
public class CalculadoraCompleta extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraCompleta
     */
    public CalculadoraCompleta() {
        initComponents();
        lblRest.setVisible(false);
        lblCub.setVisible(false);
        lblRaiz.setVisible(false);
        lblRaizCub.setVisible(false);
        lblAbsoluto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        number = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        lblRest = new javax.swing.JLabel();
        lblCub = new javax.swing.JLabel();
        lblRaiz = new javax.swing.JLabel();
        lblRaizCub = new javax.swing.JLabel();
        lblAbsoluto = new javax.swing.JLabel();
        txtRest = new javax.swing.JLabel();
        txtCub = new javax.swing.JLabel();
        txtRaiz = new javax.swing.JLabel();
        txtRaizCub = new javax.swing.JLabel();
        txtAbsoluto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Super Calculadora");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        jLabel2.setText("Informe um valor:");

        number.setModel(new javax.swing.SpinnerNumberModel());

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblRest.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblRest.setText("Resto da Divisão por 2:");

        lblCub.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCub.setText("Elevado ao cubo:");

        lblRaiz.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblRaiz.setText("Raiz Quadrada:");

        lblRaizCub.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblRaizCub.setText("Raiz Cúbica:");

        lblAbsoluto.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblAbsoluto.setText("Valor absoluto:");

        txtRest.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txtRest.setForeground(java.awt.SystemColor.activeCaption);

        txtCub.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txtCub.setForeground(java.awt.SystemColor.activeCaption);

        txtRaiz.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txtRaiz.setForeground(java.awt.SystemColor.activeCaption);

        txtRaizCub.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txtRaizCub.setForeground(java.awt.SystemColor.activeCaption);

        txtAbsoluto.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txtAbsoluto.setForeground(java.awt.SystemColor.activeCaption);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRest)
                            .addComponent(lblCub)
                            .addComponent(lblRaiz)
                            .addComponent(lblRaizCub)
                            .addComponent(lblAbsoluto))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAbsoluto)
                            .addComponent(txtRaizCub)
                            .addComponent(txtRaiz)
                            .addComponent(txtCub)
                            .addComponent(txtRest)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1)
                    .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRest)
                    .addComponent(txtRest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCub)
                    .addComponent(txtCub))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRaiz)
                    .addComponent(txtRaiz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRaizCub)
                    .addComponent(txtRaizCub))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAbsoluto)
                    .addComponent(txtAbsoluto))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        lblRest.setVisible(true);
        lblCub.setVisible(true);
        lblRaiz.setVisible(true);
        lblRaizCub.setVisible(true);
        lblAbsoluto.setVisible(true);
        
        int valor = (int) number.getValue();
        float restoDivisao = valor%2;
        int elevadoCubo = (int) Math.pow(valor, 3);
        float raizQuadrada = (float) Math.sqrt(valor);
        float raizCubica = (float) Math.cbrt(valor);
        
        txtRest.setText(Float.toString(restoDivisao));
        txtCub.setText(Integer.toString(elevadoCubo));
        txtRaiz.setText(Float.toString(raizQuadrada));
        txtRaizCub.setText(Float.toString(raizCubica));
        txtAbsoluto.setText(Integer.toString(valor));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraCompleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAbsoluto;
    private javax.swing.JLabel lblCub;
    private javax.swing.JLabel lblRaiz;
    private javax.swing.JLabel lblRaizCub;
    private javax.swing.JLabel lblRest;
    private javax.swing.JSpinner number;
    private javax.swing.JLabel txtAbsoluto;
    private javax.swing.JLabel txtCub;
    private javax.swing.JLabel txtRaiz;
    private javax.swing.JLabel txtRaizCub;
    private javax.swing.JLabel txtRest;
    // End of variables declaration//GEN-END:variables
}
